### ISSUE TITLE
[BUG - Release] UE4SS Error: bad conversion ConsoleCommandsMod/BPModLoaderMod

### ISSUE THREAD

**Issue by Wooolfik** [UE4SS-RE/RE-UE4SS#499]
**Game and Engine Version**
tried with 3.0.1 and 3.0.0 UE4SS
Palworld - v0.2.3.0

**Describe the bug**
UE4SS does not seem to work, none of the mods that require it work, when checking console in game log ends with 
**Starting Lua mod 'ConsoleCommandsMod'
Error: bad conversion**
if "ConsoleCommandsMod" is disabled log ends with
**Starting Lua mod 'BPModLoaderMod'
Error: bad conversion**

**Mods directory**
A zip of your Mods folder if you've installed any mods that don't come with UE4SS by default
IncreasedWorldSettings200 | DekXMOG | DekModConfigMenu all 3 manually added to mods.txt and set to "1"
[Mods.zip](https://github.com/UE4SS-RE/RE-UE4SS/files/15285747/Mods.zip)

**To Reproduce**
1. Download UE4SS
2. Unzip to "...\Palworld\Pal\Binaries\Win64"
3. Lunch the game 
4. See error in log

**Expected behavior**
I expected UE4SS to work since its needed for lots of mods.

**Screenshots, UE4SS Log, and .dmp file**
Log 3.0.0 **(same happens with 3.0.1)** with mods.txt having "ConsoleCommandsMod : 1"
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/15285743/UE4SS.log)
Log 3.0.1 **(same happens with 3.0.0)** with mods.txt having "ConsoleCommandsMod : 0"
[UE4SS.log](https://github.com/UE4SS-RE/RE-UE4SS/files/15285776/UE4SS.log)
couldn't find any .dmp file

**Desktop:**
 - Win10

**Additional context**
changed 
bUseUObjectArrayCache = false (from true, caused crashes on world start)
GraphicsAPI = dx11 (from opengl, in-game log window was just white color)
in UE4SS-settings.ini 

Log ends with

> ##### MEMBER OFFSETS END #####
> 
> [2024-05-12 10:02:45] m_shared_functions: 0x7fff6ae33b60
> [2024-05-12 10:02:45] Enabling custom events
> [2024-05-12 10:02:45] Starting mods (from mods.txt load order)...
> [2024-05-12 10:02:45] Starting Lua mod 'CheatManagerEnablerMod'
> [2024-05-12 10:02:45] [RegisterHook] Registered native hook (1, 2) for Function /Script/Engine.PlayerController:ClientRestart
> [2024-05-12 10:02:45] Mod 'ActorDumperMod' disabled in mods.txt.
> [2024-05-12 10:02:45] Mod 'ConsoleCommandsMod' disabled in mods.txt.
> [2024-05-12 10:02:45] Starting Lua mod 'ConsoleEnablerMod'
> [2024-05-12 10:02:46] [Lua] [ConsoleEnabler] ConsoleKey[1]: F10
> [2024-05-12 10:02:46] [Lua] [ConsoleEnabler] ConsoleKey[2]: @
> [2024-05-12 10:02:46] Mod 'SplitScreenMod' disabled in mods.txt.
> [2024-05-12 10:02:46] Mod 'LineTraceMod' disabled in mods.txt.
> [2024-05-12 10:02:46] Starting Lua mod 'BPModLoaderMod'
> [2024-05-12 10:02:46] Error: bad conversion
> [2024-05-12 10:02:46] Event loop start

**Comment by UE4SS** [comment]
I believe this should be fixed, but not yet officially released.
Could you try this experimental build to confirm that it's fixed ? https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/zDEV-UE4SS_v3.0.1-67-g666b477.zip

**Comment by Wooolfik** [comment]
> I believe this should be fixed, but not yet officially released. Could you try this experimental build to confirm that it's fixed ? https://github.com/UE4SS-RE/RE-UE4SS/releases/download/experimental/zDEV-UE4SS_v3.0.1-67-g666b477.zip

Hey, 
thanks for quick reply,
sadly I still get the same error
![image](https://github.com/UE4SS-RE/RE-UE4SS/assets/90418746/8e85e703-77ff-4bbc-9fc0-a91c57fb04dd)

**Comment by Wooolfik** [comment]
Seems like restarting PC actually repaired it, experimental build works for me now. Thanks.
