### ISSUE TITLE
Two versions running + Steam screenshot issue

### ISSUE THREAD

**Issue by WicCaesar** [UE4SS-RE/RE-UE4SS#83]
Hello! I had the standard RE-UE4SS installed and working, but then was needed the dev version. I thought I had replaced everything, but apparently not, since now I run both versions whenever I run the game [<image>](https://i.imgur.com/YgaorjT.png).

Also, the dev version seems to interfere with NVIDIA Ansel (either it makes the interface small, occupying only part of the screen, or if it is the normal size, it restricts mouse movement to that small part) and also Steam's screenshot feature (whenever I press F12 to take a screenshot, it's actually capturing RE-UE4SS's interface [<image>](https://i.imgur.com/6er8Tqo.png).

Is there any fix or workaround for the screenshot issue, at least? The other two I can live with. Thanks in advance.

**Comment by UE4SS** [comment]
For the first problem; It's not running two versions, it's opening both a standard Windows console and the dev ui.
The standard Windows console receives all output from UE4SS and also all output from the game.
The dev ui only receives output from UE4SS.

For the second & third problems; I don't really have a good answer here.
You could try to close the dev ui by clicking the `X` to close the window, and when you need it again, hit CTRL + O to open it.
You can also try changing `GuiConsoleVisible` to `0` in UE4SS-settings.ini under the `[Debug]` section.
That will stop the dev ui from opening automatically but you can still open it by hitting CTRL + O.
If there's still a problem, then try also setting `GuiConsoleEnabled` to 0 which will entirely disable the dev ui which means you won't be able to open it with CTRL + O.

**Comment by DAOWAce** [comment]
I wrote out an issue about this, but never got around to posting it.

The default changed to a GUI in 2.50.  It used to be a console.

Having a GUI results things like the Steam overlay injecting into UE4SS instead of the game being launched by it.

There is no fix I know of besides editing the config file to revert back to only opening a console window.

**Comment by narknon** [comment]
I've made a branch to experiment with adding a deferred spawn to the GUI.  It seems to fix the nvidia issue, but steam always just swaps to it when it spawns later.

**Comment by narknon** [comment]
I'll likely revert the default back to not using the debug GUI and come up with some other solution for mod buttons.

**Comment by narknon** [comment]
The debug GUI is no longer visible by default, so this should not be an issue for most end users.  Leaving open in case we want to do a more robust fix eventually.

**Comment by RenaKunisaki** [comment]
I ran into the screenshot problem, so I tried closing the debug UI and taking a screenshot, and the game (Palworld) immediately crashed.

**Comment by Buckminsterfullerene02** [comment]
> I ran into the screenshot problem, so I tried closing the debug UI and taking a screenshot, and the game (Palworld) immediately crashed. The screenshot did save properly though.

This big has been fixed in 3.0.1.

**Comment by RenaKunisaki** [comment]
Not for me it hasn't. I can close the debug UI, but taking a screenshot still crashes the game.

**Comment by UE4SS** [comment]
> Not for me it hasn't. I can close the debug UI, but taking a screenshot still crashes the game.

Make a new issue, this seems like a different problem.
